query WarrantyOrderForm {
  orderForm @context(provider: "vtex.store-graphql") {
    cacheId
    orderFormId
    value
    totalizers {
      id
      name
      value
    }
    customData {
      customApps {
        id
        fields
      }
    }
    itemMetadata {
      items {
        id
        name
        skuName
        productId
        refId
        ean
        seller
        imageUrl
        assemblyOptions {
          id
          name
          required
          composition {
            minQuantity
            maxQuantity
            items {
              id
              minQuantity
              maxQuantity
              initialQuantity
              priceTable
              seller
            }
          }
        }
      }
      priceTable {
        type
        values {
          id
          price
        }
      }
    }
    items {
      id
      name
      imageUrl
      detailUrl
      skuName
      quantity
      sellingPrice
      listPrice
      parentItemIndex
      parentAssemblyBinding
      cartIndex
      assemblyOptions {
        added {
          item {
            name
            sellingPrice
            quantity
          }
          normalizedQuantity
          choiceType
          extraQuantity
        }
        removed {
          removedQuantity
          initialQuantity
          name
        }
        parentPrice
      }
      seller
    }
    shippingData {
      address {
        id
        neighborhood
        complement
        number
        street
        postalCode
        city
        reference
        addressName
        addressType
        geoCoordinates
        state
        receiverName
        country
      }
      availableAddresses {
        id
        neighborhood
        complement
        number
        street
        postalCode
        city
        reference
        addressName
        addressType
        geoCoordinates
        state
        receiverName
        country
      }
    }
    clientProfileData {
      email
      firstName
    }
    storePreferencesData {
      countryCode
      currencyCode
      timeZone
    }
    checkedInPickupPointId
    isCheckedIn
  }
}